"""initial content schema

Revision ID: 0001_content_initial
Revises:
Create Date: 2026-09-18

The autogenerated block is followed by the PL/pgSQL triggers: pages, reviews, events, gold
protocols and AI runs are append-only; documents, segments and protocols may only change
their status (docs/MIGRATIONS.md, docs/CONTENT_PIPELINE.md).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ari.infrastructure.persistence import ddl

revision: str = "0001_content_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("uploaded_via", sa.String(), nullable=False),
        sa.Column("uploaded_by_account_id", sa.String(), nullable=True),
        sa.Column("declared_land", sa.String(), nullable=True),
        sa.Column("declared_city", sa.String(), nullable=True),
        sa.Column("declared_exam_body", sa.String(), nullable=True),
        sa.Column("declared_exam_date", sa.String(length=7), nullable=True),
        sa.Column("declared_specialty", sa.String(), nullable=True),
        sa.Column("provenance", sa.Text(), nullable=False),
        sa.Column("rights", sa.String(), nullable=False),
        sa.Column("rights_evidence", sa.Text(), nullable=True),
        sa.Column("intended_use", sa.Text(), nullable=False),
        sa.Column("consent_declaration", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "declared_land IS NULL OR declared_land IN ('Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen')",
            name="ck_document_land",
        ),
        sa.CheckConstraint(
            "rights IN ('unknown', 'incompatible', 'compatible')", name="ck_document_rights"
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'text_extracted', 'segmented', 'extracted', 'failed')",
            name="ck_document_status",
        ),
        sa.CheckConstraint(
            "uploaded_via IN ('cli', 'backoffice')", name="ck_document_uploaded_via"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_table(
        "document_pages",
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("char_count", sa.Integer(), nullable=False),
        sa.Column("extractor", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_document_pages_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("document_id", "page_number", name=op.f("pk_document_pages")),
    )
    op.create_table(
        "document_segments",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column("page_from", sa.Integer(), nullable=False),
        sa.Column("page_to", sa.Integer(), nullable=False),
        sa.Column("start_marker", sa.Text(), nullable=False),
        sa.Column("title_hint", sa.String(), nullable=True),
        sa.Column("date_hint", sa.String(), nullable=True),
        sa.Column("land_hint", sa.String(), nullable=True),
        sa.Column("city_hint", sa.String(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("ai_run_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("origin IN ('ai', 'manual')", name="ck_segment_origin"),
        sa.CheckConstraint(
            "status IN ('pending', 'extracted', 'failed', 'too_long', 'discarded')",
            name="ck_segment_status",
        ),
        sa.CheckConstraint("page_from >= 1 AND page_to >= page_from", name="ck_segment_pages"),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_segments_document_id_documents"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_segments")),
        sa.UniqueConstraint("document_id", "index", name="uq_segment_document_index"),
    )
    op.create_index(
        op.f("ix_document_segments_document_id"), "document_segments", ["document_id"], unique=False
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column("protocol_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'dead')", name="ck_job_status"
        ),
        sa.CheckConstraint(
            "type IN ('extract_text', 'segment_document', 'extract_protocol', 'generate_bundle_draft')",
            name="ck_job_type",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_jobs_document_id_documents")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(op.f("ix_jobs_document_id"), "jobs", ["document_id"], unique=False)
    op.create_index("ix_jobs_status_available_at", "jobs", ["status", "available_at"], unique=False)
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=True),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("prompt_hash", sa.String(length=64), nullable=True),
        sa.Column("schema_name", sa.String(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=True),
        sa.Column("segment_id", sa.String(), nullable=True),
        sa.Column("protocol_id", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_request_id", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_ai_runs_document_id_documents")
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_ai_runs_job_id_jobs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_index(op.f("ix_ai_runs_document_id"), "ai_runs", ["document_id"], unique=False)
    op.create_index(op.f("ix_ai_runs_job_id"), "ai_runs", ["job_id"], unique=False)
    op.create_table(
        "protocols",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("segment_id", sa.String(), nullable=False),
        sa.Column("page_from", sa.Integer(), nullable=False),
        sa.Column("page_to", sa.Integer(), nullable=False),
        sa.Column("parent_version", sa.Integer(), nullable=True),
        sa.Column("created_via", sa.String(), nullable=False),
        sa.Column("created_by_account_id", sa.String(), nullable=True),
        sa.Column("pii_findings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("pii_detector_version", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "created_via IN ('ai', 'doctor', 'owner')", name="ck_protocol_created_via"
        ),
        sa.CheckConstraint(
            "status IN ('extracted', 'doctor_review', 'changes_requested', 'doctor_approved', 'gold', 'rejected', 'superseded')",
            name="ck_protocol_status",
        ),
        sa.CheckConstraint("version >= 1", name="ck_protocol_version"),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_protocols_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["segment_id"],
            ["document_segments.id"],
            name=op.f("fk_protocols_segment_id_document_segments"),
        ),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_protocols")),
        sa.UniqueConstraint("id", "version", "content_hash", name="uq_protocol_identity_hash"),
    )
    op.create_index(op.f("ix_protocols_document_id"), "protocols", ["document_id"], unique=False)
    op.create_table(
        "gold_protocols",
        sa.Column("protocol_id", sa.String(), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("protocol_hash", sa.String(length=64), nullable=False),
        sa.Column("gold_hash", sa.String(length=64), nullable=False),
        sa.Column("land", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("exam_body", sa.String(), nullable=True),
        sa.Column("exam_date", sa.String(length=7), nullable=True),
        sa.Column("specialty", sa.String(), nullable=True),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("frozen_by_account_id", sa.String(), nullable=True),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "land IN ('Baden-Württemberg', 'Bayern', 'Berlin', 'Brandenburg', 'Bremen', 'Hamburg', 'Hessen', 'Mecklenburg-Vorpommern', 'Niedersachsen', 'Nordrhein-Westfalen', 'Rheinland-Pfalz', 'Saarland', 'Sachsen', 'Sachsen-Anhalt', 'Schleswig-Holstein', 'Thüringen')",
            name="ck_gold_land",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"], ["documents.id"], name=op.f("fk_gold_protocols_document_id_documents")
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id", "protocol_version", "protocol_hash"],
            ["protocols.id", "protocols.version", "protocols.content_hash"],
            name=op.f("fk_gold_protocols_protocol_id_protocols"),
        ),
        sa.PrimaryKeyConstraint("protocol_id", name=op.f("pk_gold_protocols")),
        sa.UniqueConstraint("gold_hash", name=op.f("uq_gold_protocols_gold_hash")),
    )
    op.create_table(
        "protocol_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("protocol_id", sa.String(), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("actor_kind", sa.String(), nullable=False),
        sa.Column("actor_account_id", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "actor_kind IN ('system', 'account', 'cli')", name="ck_event_actor_kind"
        ),
        sa.ForeignKeyConstraint(
            ["protocol_id", "protocol_version"],
            ["protocols.id", "protocols.version"],
            name=op.f("fk_protocol_events_protocol_id_protocols"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protocol_events")),
    )
    op.create_index(
        op.f("ix_protocol_events_protocol_id"), "protocol_events", ["protocol_id"], unique=False
    )
    op.create_table(
        "protocol_reviews",
        sa.Column("sequence", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("protocol_id", sa.String(), nullable=False),
        sa.Column("protocol_version", sa.Integer(), nullable=False),
        sa.Column("protocol_hash", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("decision", sa.String(), nullable=False),
        sa.Column("reviewer_account_id", sa.String(), nullable=False),
        sa.Column("reviewer_name", sa.String(), nullable=False),
        sa.Column("pii_override_note", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision IN ('approve', 'request_changes', 'reject')",
            name="ck_protocol_review_decision",
        ),
        sa.CheckConstraint("stage IN ('doctor', 'owner')", name="ck_protocol_review_stage"),
        sa.ForeignKeyConstraint(
            ["protocol_id", "protocol_version", "protocol_hash"],
            ["protocols.id", "protocols.version", "protocols.content_hash"],
            name=op.f("fk_protocol_reviews_protocol_id_protocols"),
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_protocol_reviews")),
        sa.UniqueConstraint("id", name=op.f("uq_protocol_reviews_id")),
    )
    # ### end Alembic commands ###
    _create_triggers()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("protocol_reviews")
    op.drop_index(op.f("ix_protocol_events_protocol_id"), table_name="protocol_events")
    op.drop_table("protocol_events")
    op.drop_table("gold_protocols")
    op.drop_index(op.f("ix_protocols_document_id"), table_name="protocols")
    op.drop_table("protocols")
    op.drop_index(op.f("ix_ai_runs_job_id"), table_name="ai_runs")
    op.drop_index(op.f("ix_ai_runs_document_id"), table_name="ai_runs")
    op.drop_table("ai_runs")
    op.drop_index("ix_jobs_status_available_at", table_name="jobs")
    op.drop_index(op.f("ix_jobs_document_id"), table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(op.f("ix_document_segments_document_id"), table_name="document_segments")
    op.drop_table("document_segments")
    op.drop_table("document_pages")
    op.drop_table("documents")
    # ### end Alembic commands ###
    op.execute(ddl.DROP_ONLY_COLUMNS_MUTABLE_FUNCTION)
    op.execute(ddl.DROP_IMMUTABLE_FUNCTION)


APPEND_ONLY_TABLES = (
    "document_pages",
    "protocol_reviews",
    "protocol_events",
    "gold_protocols",
    "ai_runs",
)
# Content rows whose status (and bookkeeping) moves while their content never does.
GUARDED_TABLES: dict[str, tuple[str, ...]] = {
    "documents": ("status", "page_count", "updated_at"),
    "document_segments": ("status",),
    "protocols": ("status",),
}


def _create_triggers() -> None:
    op.execute(ddl.IMMUTABLE_FUNCTION)
    op.execute(ddl.ONLY_COLUMNS_MUTABLE_FUNCTION)
    ddl.create_append_only_triggers(op, APPEND_ONLY_TABLES, "Content is append-only")
    for table, columns in GUARDED_TABLES.items():
        ddl.create_column_guard(op, table, columns, "Content rows are never deleted")
