"""backoffice accounts, invitations, sessions, audit

Revision ID: 0002_backoffice_auth
Revises: 0001_content_initial
Create Date: 2026-09-18

The audit table is append-only (trigger); accounts, invitations and sessions are mutable
bookkeeping (lockout counters, used and revoked timestamps).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ari.infrastructure.persistence import ddl

revision: str = "0002_backoffice_auth"
down_revision: str | Sequence[str] | None = "0001_content_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "backoffice_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("roles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("email = lower(email)", name="ck_account_email_lower"),
        sa.CheckConstraint("jsonb_array_length(roles) > 0", name="ck_account_roles"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backoffice_accounts")),
        sa.UniqueConstraint("email", name=op.f("uq_backoffice_accounts_email")),
    )
    op.create_table(
        "backoffice_audit",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("actor_account_id", sa.String(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backoffice_audit")),
    )
    op.create_table(
        "backoffice_invitations",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_account_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["backoffice_accounts.id"],
            name=op.f("fk_backoffice_invitations_account_id_backoffice_accounts"),
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_backoffice_invitations")),
    )
    op.create_index(
        op.f("ix_backoffice_invitations_account_id"),
        "backoffice_invitations",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "backoffice_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["backoffice_accounts.id"],
            name=op.f("fk_backoffice_sessions_account_id_backoffice_accounts"),
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_backoffice_sessions")),
    )
    op.create_index(
        op.f("ix_backoffice_sessions_account_id"),
        "backoffice_sessions",
        ["account_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    ddl.create_append_only_triggers(op, ("backoffice_audit",), "Audit is append-only")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_backoffice_sessions_account_id"), table_name="backoffice_sessions")
    op.drop_table("backoffice_sessions")
    op.drop_index(op.f("ix_backoffice_invitations_account_id"), table_name="backoffice_invitations")
    op.drop_table("backoffice_invitations")
    op.drop_table("backoffice_audit")
    op.drop_table("backoffice_accounts")
    # ### end Alembic commands ###
