"""bundle drafts generated from gold protocols

Revision ID: 0003_bundle_drafts
Revises: 0002_backoffice_auth
Create Date: 2026-09-20

A draft is frozen content; only `status` and `imported_at` may change and rows are never deleted.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ari.infrastructure.persistence import ddl

revision: str = "0003_bundle_drafts"
down_revision: str | Sequence[str] | None = "0002_backoffice_auth"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bundle_drafts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("gold_protocol_id", sa.String(), nullable=False),
        sa.Column("gold_hash", sa.String(length=64), nullable=False),
        sa.Column("request", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("bundle", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("bundle_hash", sa.String(length=64), nullable=True),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("case_version", sa.String(), nullable=True),
        sa.Column("scenario_refs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validation_errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_run_id", sa.String(), nullable=True),
        sa.Column("created_by_account_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'invalid') = (bundle IS NULL)", name="ck_bundle_draft_bundle_presence"
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'invalid', 'imported')", name="ck_bundle_draft_status"
        ),
        sa.ForeignKeyConstraint(
            ["ai_run_id"], ["ai_runs.id"], name=op.f("fk_bundle_drafts_ai_run_id_ai_runs")
        ),
        sa.ForeignKeyConstraint(
            ["gold_protocol_id"],
            ["gold_protocols.protocol_id"],
            name=op.f("fk_bundle_drafts_gold_protocol_id_gold_protocols"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bundle_drafts")),
    )
    op.create_index(
        op.f("ix_bundle_drafts_gold_protocol_id"),
        "bundle_drafts",
        ["gold_protocol_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    ddl.create_column_guard(
        op, "bundle_drafts", ("status", "imported_at"), "Bundle drafts are never deleted"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bundle_drafts_gold_protocol_id"), table_name="bundle_drafts")
    op.drop_table("bundle_drafts")
    # ### end Alembic commands ###
