from typing import Protocol

from ari.domain.practice import PracticeAnswer, PracticeContent, PracticeFeedback, PracticeRun


class PracticeCatalog(Protocol):
    def list(self) -> tuple[PracticeContent, ...]: ...

    def get(self, scenario_id: str, version: str) -> PracticeContent: ...


class PracticeRepository(Protocol):
    def create(self, run: PracticeRun) -> PracticeRun: ...

    def find_request(self, learner_id: str, request_id: str) -> PracticeRun | None: ...

    def get(self, run_id: str, learner_id: str) -> PracticeRun: ...

    def get_any(self, run_id: str) -> PracticeRun: ...

    def list(self, learner_id: str) -> tuple[PracticeRun, ...]: ...

    def append_answer(
        self, run_id: str, learner_id: str, answer: PracticeAnswer
    ) -> PracticeRun: ...

    def set_paused(self, run_id: str, learner_id: str, paused: bool) -> PracticeRun: ...

    def finish(
        self, run_id: str, learner_id: str, feedback: PracticeFeedback, expected_answer_count: int
    ) -> PracticeRun: ...
