"""PDF → text → segments → protocol drafts, offline, with every model call traced."""

from __future__ import annotations

import asyncio
from dataclasses import replace
from pathlib import Path

import pytest
from content_fixtures import synthetic_protocol_pdf
from sqlalchemy import text as sql_text

from ari.content.container import ContentContainer
from ari.content.domain.documents import (
    Actor,
    Document,
    DocumentDeclaration,
    DocumentSegment,
    DocumentStatus,
    JobStatus,
)
from ari.content.domain.protocol import ProtocolStatus
from ari.content.fake_handlers import extraction as fake_extraction
from ari.content.ports import PdfText
from ari.content.schemas import ExtractionOutput, SegmentationSpan
from ari.content.services.extraction import draft_record
from ari.content.services.segmentation import merge_spans, windows
from ari.content.services.text_extraction import TextExtraction
from ari.domain.errors import InvalidStateError
from ari.domain.geography import Land
from ari.worker import run_one

OPERATOR = Actor(kind="cli", name="operator", account_id="cli-operator")


class NulTextExtractor:
    def extract(self, path: Path) -> PdfText:
        del path
        return PdfText(page_count=1, pages=("Vorher\x00Nachher",), extractor="test")

    def render_page(self, path: Path, page_number: int, *, dpi: int = 110) -> bytes:
        del path, page_number, dpi
        return b""


def declaration(**overrides: object) -> DocumentDeclaration:
    base = DocumentDeclaration(
        provenance="Synthetic PDF generated by the test suite",
        intended_use="tests",
        consent_declaration="No real person involved",
        rights="compatible",
        rights_evidence="Generated fixture",
        land=Land.BAYERN,
    )
    return replace(base, **overrides)  # type: ignore[arg-type]


def drain(container: ContentContainer) -> int:
    async def loop() -> int:
        processed = 0
        while await run_one(container, "test-worker") is not None:
            processed += 1
        return processed

    return asyncio.run(loop())


def test_pdf_becomes_traced_protocol_drafts(
    content_container: ContentContainer, tmp_path: Path
) -> None:
    pdf = synthetic_protocol_pdf(tmp_path / "protokolle.pdf", count=3)
    result = content_container.ingestion.ingest(
        pdf.read_bytes(), pdf.name, declaration(), actor=OPERATOR, via="cli"
    )
    assert result.duplicate is False
    assert content_container.storage.exists(result.document.storage_key)
    assert [job.type.value for job in content_container.queue.list()] == ["extract_text"]

    processed = drain(content_container)
    assert processed == 1 + 1 + 3  # text, segmentation, one extraction per protocol
    with content_container.repository.transaction() as tx:
        document = tx.get_document(result.document.id)
        assert document is not None and document.status is DocumentStatus.EXTRACTED
        assert document.page_count == 4
        segments = tx.segments(document.id)
        assert [s.page_from for s in segments] == [2, 3, 4]
        assert all(s.status.value == "extracted" for s in segments)
        heads = tx.list_heads(document_id=document.id)
        assert [h.id for h in heads] == [f"P-{document.id[:8]}-00{i}" for i in range(3)]
        assert all(h.status is ProtocolStatus.EXTRACTED and h.version == 1 for h in heads)
        first = heads[0].record
        assert first.location.land is Land.BAYERN and first.location.city is None
        assert first.source.city_hint == "München" and first.patient.age_years == 41
        assert first.anamnesis[0].section == "aktuelle_beschwerden"
        assert first.review_blockers("doctor")  # the draft still asks the doctor a question
        runs = tx.ai_runs(document_id=document.id)
        assert {r.operation for r in runs} == {"protocol_segmentation", "protocol_extraction"}
        assert all(r.prompt_hash and r.input_hash and r.status == "succeeded" for r in runs)
        assert {r.prompt_version for r in runs} == {"segmentation-v1", "protocol-extraction-v2"}
        assert [e.event_type for e in tx.events(heads[0].id)] == ["extracted"]
    assert all(job.status is JobStatus.SUCCEEDED for job in content_container.queue.list())

    again = content_container.ingestion.ingest(
        pdf.read_bytes(), "copy.pdf", declaration(), actor=OPERATOR, via="cli"
    )
    assert again.duplicate is True and again.document.id == result.document.id
    assert len(content_container.queue.list()) == 5  # no new job for the same bytes


def test_text_extraction_removes_nul_bytes_before_persistence(
    content_container: ContentContainer, tmp_path: Path
) -> None:
    pdf = synthetic_protocol_pdf(tmp_path / "nul.pdf", count=1)
    result = content_container.ingestion.ingest(
        pdf.read_bytes(), pdf.name, declaration(), actor=OPERATOR, via="cli"
    )
    job = content_container.queue.list()[0]

    TextExtraction(
        content_container.repository,
        content_container.storage,
        NulTextExtractor(),
        content_container.queue,
    ).run(job)

    with content_container.repository.transaction() as tx:
        pages = tx.pages(result.document.id)
        assert len(pages) == 1
        assert pages[0].text == "Vorher\ufffdNachher"
        assert pages[0].char_count == len("Vorher\ufffdNachher")
        assert "\x00" not in pages[0].text

    with content_container.repository.engine.connect() as connection:  # type: ignore[attr-defined]
        row = connection.execute(
            sql_text(
                "SELECT text, char_count FROM document_pages WHERE document_id = :document_id"
            ),
            {"document_id": result.document.id},
        ).one()
        assert row.text == "Vorher\ufffdNachher"
        assert row.char_count == len("Vorher\ufffdNachher")


def test_draft_record_normalises_unknown_anamnesis_value() -> None:
    output = ExtractionOutput.model_validate(fake_extraction({"text": ""}))
    output = output.model_copy(
        update={
            "anamnesis": [
                output.anamnesis[0].model_copy(
                    update={
                        "value_de": "Unklare Angabe",
                        "polarity": "unknown",
                        "uncertainty": "Source ambiguë",
                    }
                )
            ]
        }
    )
    document = Document(
        id="d" * 64,
        filename="protocol.pdf",
        size_bytes=1,
        storage_key="test.pdf",
        uploaded_via="cli",
        declaration=declaration(),
    )
    segment = DocumentSegment(
        id="segment-1",
        document_id=document.id,
        index=0,
        page_from=1,
        page_to=1,
        start_marker="Protokoll",
        confidence=1.0,
        origin="ai",
    )

    record = draft_record(output, document=document, segment=segment)

    assert record.anamnesis[0].value_de is None
    assert record.anamnesis[0].polarity == "unknown"
    assert record.anamnesis[0].uncertainty == (
        "Source ambiguë — Valeur extraite avec polarité inconnue : Unklare Angabe"
    )


def test_segmentation_without_spans_fails_the_document(
    content_container: ContentContainer, tmp_path: Path
) -> None:
    import pymupdf

    pdf = pymupdf.open()
    pdf.new_page().insert_text((72, 72), "Document sans protocole FSP")
    path = tmp_path / "no-protocol.pdf"
    pdf.save(path)
    pdf.close()
    result = content_container.ingestion.ingest(
        path.read_bytes(), path.name, declaration(), actor=OPERATOR, via="cli"
    )

    assert asyncio.run(run_one(content_container, "test-worker")) is not None
    failed = asyncio.run(run_one(content_container, "test-worker"))

    assert failed is not None and failed.status is JobStatus.DEAD
    assert "La segmentation n'a produit aucun segment" in (failed.last_error or "")
    with content_container.repository.transaction() as tx:
        document = tx.get_document(result.document.id)
        assert document is not None and document.status is DocumentStatus.FAILED
        assert tx.segments(document.id) == ()
        assert len(tx.ai_runs(document_id=document.id)) == 1


def test_ingestion_refuses_non_pdf_and_oversize_files(content_container: ContentContainer) -> None:
    with pytest.raises(InvalidStateError, match="PDF"):
        content_container.ingestion.ingest(
            b"hello", "x.pdf", declaration(), actor=OPERATOR, via="cli"
        )
    huge = b"%PDF-1.7" + b"0" * content_container.settings.content_upload_max_bytes
    with pytest.raises(InvalidStateError, match="volumineux"):
        content_container.ingestion.ingest(huge, "x.pdf", declaration(), actor=OPERATOR, via="cli")


def test_windows_overlap_and_own_pages() -> None:
    assert windows(4) == [(1, 4, 1)]
    assert windows(25) == [(1, 25, 1)]
    assert windows(30) == [(1, 25, 1), (24, 30, 26)]
    assert windows(60) == [(1, 25, 1), (24, 48, 26), (47, 60, 49)]


def _span(page_from: int, page_to: int, marker: str) -> SegmentationSpan:
    return SegmentationSpan(
        page_from=page_from,
        page_to=page_to,
        start_marker=marker,
        title_hint=None,
        date_hint=None,
        land_hint=None,
        city_hint=None,
        confidence=0.9,
        notes=None,
    )


def test_merge_spans_dedupes_overlap_and_makes_protocols_contiguous() -> None:
    pages = {n: f"Protokoll {n} text" for n in range(1, 31)}
    pages[10] = "Protokoll A ... Protokoll B"
    collected = [
        (_span(2, 5, "Protokoll 2 text"), 25),
        (_span(10, 10, "Protokoll A"), 25),
        (_span(10, 10, "Protokoll B"), 25),
        (_span(24, 25, "Protokoll 24 text"), 25),  # hit the window end: continues
        (_span(24, 25, "Protokoll  24 text"), 30),  # same protocol seen from the next window
        (_span(28, 28, "Protokoll 28 text"), 30),
    ]
    drafts = merge_spans(collected, pages, 30)
    assert [(d.span.page_from, d.page_to, d.span.start_marker) for d in drafts] == [
        (2, 9, "Protokoll 2 text"),
        (10, 10, "Protokoll A"),
        (10, 23, "Protokoll B"),
        (24, 27, "Protokoll 24 text"),
        (28, 28, "Protokoll 28 text"),
    ]
