"""initial platform schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-18

The autogenerated block is followed by the PL/pgSQL triggers that keep published clinical
content, reviews, answers and receipts append-only (docs/MIGRATIONS.md).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from ari.infrastructure.persistence import ddl

revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_clinical_cases")),
        sa.UniqueConstraint(
            "id", "version", "content_hash", name=op.f("uq_clinical_cases_id_version_content_hash")
        ),
    )
    op.create_table(
        "clinical_rubrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_clinical_rubrics")),
        sa.UniqueConstraint(
            "id",
            "version",
            "content_hash",
            name=op.f("uq_clinical_rubrics_id_version_content_hash"),
        ),
    )
    op.create_table(
        "clinical_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_sources")),
    )
    op.create_table(
        "clinical_terminology",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_clinical_terminology")),
        sa.UniqueConstraint(
            "id",
            "version",
            "content_hash",
            name=op.f("uq_clinical_terminology_id_version_content_hash"),
        ),
    )
    op.create_table(
        "learners",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learners")),
    )
    op.create_table(
        "placement_sets",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("language", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.CheckConstraint(
            "status IN ('draft_unvalidated', 'published', 'withdrawn')",
            name="ck_placement_workflow_status",
        ),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_placement_sets")),
        sa.UniqueConstraint(
            "id", "version", "content_hash", name=op.f("uq_placement_sets_id_version_content_hash")
        ),
    )
    op.create_table(
        "placement_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_sources")),
    )
    op.create_table(
        "clinical_case_sources",
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id", "case_version"],
            ["clinical_cases.id", "clinical_cases.version"],
            name=op.f("fk_clinical_case_sources_case_id_clinical_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["clinical_sources.id"],
            name=op.f("fk_clinical_case_sources_source_id_clinical_sources"),
        ),
        sa.PrimaryKeyConstraint(
            "case_id", "case_version", "source_id", name=op.f("pk_clinical_case_sources")
        ),
    )
    op.create_table(
        "clinical_scenarios",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(length=64), nullable=False),
        sa.Column("rubric_id", sa.String(), nullable=False),
        sa.Column("rubric_version", sa.String(), nullable=False),
        sa.Column("rubric_hash", sa.String(length=64), nullable=False),
        sa.Column("terminology_id", sa.String(), nullable=False),
        sa.Column("terminology_version", sa.String(), nullable=False),
        sa.Column("terminology_hash", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.CheckConstraint(
            "phase IN ('arzt_patient', 'arzt_arzt', 'fachbegriffe', 'arztbrief')",
            name="ck_clinical_phase",
        ),
        sa.CheckConstraint(
            "status IN ('draft_unvalidated', 'published', 'withdrawn')",
            name="ck_clinical_workflow_status",
        ),
        sa.ForeignKeyConstraint(
            ["case_id", "case_version", "case_hash"],
            ["clinical_cases.id", "clinical_cases.version", "clinical_cases.content_hash"],
            name=op.f("fk_clinical_scenarios_case_id_clinical_cases"),
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id", "rubric_version", "rubric_hash"],
            ["clinical_rubrics.id", "clinical_rubrics.version", "clinical_rubrics.content_hash"],
            name=op.f("fk_clinical_scenarios_rubric_id_clinical_rubrics"),
        ),
        sa.ForeignKeyConstraint(
            ["terminology_id", "terminology_version", "terminology_hash"],
            [
                "clinical_terminology.id",
                "clinical_terminology.version",
                "clinical_terminology.content_hash",
            ],
            name=op.f("fk_clinical_scenarios_terminology_id_clinical_terminology"),
        ),
        sa.PrimaryKeyConstraint("id", "version", name=op.f("pk_clinical_scenarios")),
        sa.UniqueConstraint(
            "id",
            "version",
            "content_hash",
            name=op.f("uq_clinical_scenarios_id_version_content_hash"),
        ),
    )
    op.create_index(
        "uq_clinical_published_case_phase",
        "clinical_scenarios",
        ["case_id", "case_version", "phase"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "learner_lexicon",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("lemma_key", sa.String(), nullable=False),
        sa.Column("lemma", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("srs", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_session_id", sa.String(), nullable=True),
        sa.Column("last_session_id", sa.String(), nullable=True),
        sa.Column("used_session_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("archived", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_learner_lexicon_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_lexicon")),
        sa.UniqueConstraint("learner_id", "lemma_key", name="uq_lexicon_learner_lemma"),
    )
    op.create_index(
        op.f("ix_learner_lexicon_learner_id"), "learner_lexicon", ["learner_id"], unique=False
    )
    op.create_table(
        "placement_attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("set_id", sa.String(), nullable=False),
        sa.Column("set_version", sa.String(), nullable=False),
        sa.Column("set_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column(
            "state", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "result", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "phase IN ('mcq','listening','speaking','completed')", name="ck_placement_phase"
        ),
        sa.CheckConstraint(
            "status IN ('active','completed','abandoned')", name="ck_placement_status"
        ),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_placement_attempts_learner_id_learners")
        ),
        sa.ForeignKeyConstraint(
            ["set_id", "set_version", "set_hash"],
            ["placement_sets.id", "placement_sets.version", "placement_sets.content_hash"],
            name=op.f("fk_placement_attempts_set_id_placement_sets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_attempts")),
        sa.UniqueConstraint("learner_id", "request_id", name="uq_placement_start_request"),
    )
    op.create_index(
        op.f("ix_placement_attempts_learner_id"), "placement_attempts", ["learner_id"], unique=False
    )
    op.create_table(
        "placement_publication_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("set_id", sa.String(), nullable=False),
        sa.Column("set_version", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id", "set_version"],
            ["placement_sets.id", "placement_sets.version"],
            name=op.f("fk_placement_publication_events_set_id_placement_sets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_placement_publication_events")),
    )
    op.create_table(
        "placement_reviews",
        sa.Column("sequence", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("set_id", sa.String(), nullable=False),
        sa.Column("set_version", sa.String(), nullable=False),
        sa.Column("set_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["set_id", "set_version", "set_hash"],
            ["placement_sets.id", "placement_sets.version", "placement_sets.content_hash"],
            name=op.f("fk_placement_reviews_set_id_placement_sets"),
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_placement_reviews")),
        sa.UniqueConstraint("id", name=op.f("uq_placement_reviews_id")),
    )
    op.create_table(
        "practice_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "content", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "feedback", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'completed' AND feedback IS NOT NULL AND ended_at IS NOT NULL) OR (status != 'completed' AND feedback IS NULL AND ended_at IS NULL)",
            name="ck_practice_feedback_state",
        ),
        sa.CheckConstraint("mode IN ('training','exam')", name="ck_practice_mode"),
        sa.CheckConstraint("status IN ('active','paused','completed')", name="ck_practice_status"),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_practice_runs_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_practice_runs")),
        sa.UniqueConstraint("learner_id", "request_id", name="uq_practice_start_request"),
    )
    op.create_table(
        "profile_credentials",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_profile_credentials_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_profile_credentials")),
        sa.UniqueConstraint("learner_id", name=op.f("uq_profile_credentials_learner_id")),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(), nullable=False),
        sa.Column("goal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("voice_stack_id", sa.String(), nullable=False),
        sa.Column("voice_stack_version", sa.String(), nullable=False),
        sa.Column("voice_stack_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("call_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_sessions_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
    )
    op.create_index(op.f("ix_sessions_learner_id"), "sessions", ["learner_id"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_table(
        "clinical_publication_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version"],
            ["clinical_scenarios.id", "clinical_scenarios.version"],
            name=op.f("fk_clinical_publication_events_scenario_id_clinical_scenarios"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clinical_publication_events")),
    )
    op.create_table(
        "clinical_reviews",
        sa.Column("sequence", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("scenario_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version", "scenario_hash"],
            [
                "clinical_scenarios.id",
                "clinical_scenarios.version",
                "clinical_scenarios.content_hash",
            ],
            name=op.f("fk_clinical_reviews_scenario_id_clinical_scenarios"),
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_clinical_reviews")),
        sa.UniqueConstraint("id", name=op.f("uq_clinical_reviews_id")),
    )
    op.create_table(
        "clinical_session_pins",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("scenario_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version", "scenario_hash"],
            [
                "clinical_scenarios.id",
                "clinical_scenarios.version",
                "clinical_scenarios.content_hash",
            ],
            name=op.f("fk_clinical_session_pins_scenario_id_clinical_scenarios"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_clinical_session_pins_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_clinical_session_pins")),
    )
    op.create_table(
        "evaluations",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_evaluations_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_evaluations")),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=True),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_request_id", sa.String(), nullable=True),
        sa.Column("turn_id", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_executions_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_executions")),
    )
    op.create_index(op.f("ix_executions_session_id"), "executions", ["session_id"], unique=False)
    op.create_table(
        "lexicon_reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("entry_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("rating", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["learner_lexicon.id"],
            name=op.f("fk_lexicon_reviews_entry_id_learner_lexicon"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lexicon_reviews")),
        sa.UniqueConstraint("entry_id", "event_id", name="uq_lexicon_review_event"),
    )
    op.create_index(
        op.f("ix_lexicon_reviews_entry_id"), "lexicon_reviews", ["entry_id"], unique=False
    )
    op.create_table(
        "placement_answers",
        sa.Column("attempt_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("item_id", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["placement_attempts.id"],
            name=op.f("fk_placement_answers_attempt_id_placement_attempts"),
        ),
        sa.PrimaryKeyConstraint("attempt_id", "sequence", name=op.f("pk_placement_answers")),
        sa.UniqueConstraint("attempt_id", "event_id", name="uq_placement_answer_event"),
        sa.UniqueConstraint("attempt_id", "item_id", name="uq_placement_answer_item"),
    )
    op.create_table(
        "practice_answers",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column(
            "payload", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["practice_runs.id"], name=op.f("fk_practice_answers_run_id_practice_runs")
        ),
        sa.PrimaryKeyConstraint("run_id", "question_id", name=op.f("pk_practice_answers")),
        sa.UniqueConstraint("run_id", "event_id", name="uq_practice_answer_event"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_practice_answer_sequence"),
    )
    op.create_table(
        "session_lexicon_reports",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_session_lexicon_reports_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_lexicon_reports")),
    )
    op.create_table(
        "session_metrics",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_session_metrics_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_session_metrics")),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_text", sa.Text(), nullable=False),
        sa.Column("patient_text", sa.Text(), nullable=False),
        sa.Column("revealed_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("selected_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provider_input_item_id", sa.String(), nullable=True),
        sa.Column("provider_response_id", sa.String(), nullable=True),
        sa.Column("provider_response_status", sa.String(), nullable=False),
        sa.Column("response_state", sa.String(), nullable=False),
        sa.Column("delivery_status", sa.String(), nullable=False),
        sa.Column("audio_stream_id", sa.String(), nullable=True),
        sa.Column("audio_attempt", sa.Integer(), nullable=False),
        sa.Column("expected_audio_chunks", sa.Integer(), nullable=True),
        sa.Column("audio_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("patient_response_kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["sessions.id"], name=op.f("fk_turns_session_id_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint(
            "session_id", "provider_input_item_id", name="uq_turn_session_input_item"
        ),
        sa.UniqueConstraint("session_id", "provider_response_id", name="uq_turn_session_response"),
        sa.UniqueConstraint("session_id", "sequence", name=op.f("uq_turns_session_id_sequence")),
    )
    op.create_index(
        op.f("ix_turns_provider_response_id"), "turns", ["provider_response_id"], unique=False
    )
    op.create_index(op.f("ix_turns_session_id"), "turns", ["session_id"], unique=False)
    op.create_table(
        "vocabulary_observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("lemma", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.Column(
            "evidence_turn_sequences", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_vocabulary_observations_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_observations")),
    )
    op.create_index(
        op.f("ix_vocabulary_observations_session_id"),
        "vocabulary_observations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "voice_learning_context",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.CheckConstraint("mode IN ('training','exam')", name="ck_voice_learning_mode"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_voice_learning_context_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("session_id", name=op.f("pk_voice_learning_context")),
    )
    op.create_table(
        "voice_start_requests",
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
            name=op.f("fk_voice_start_requests_learner_id_learners"),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_voice_start_requests_session_id_sessions"),
        ),
        sa.PrimaryKeyConstraint("learner_id", "request_id", name=op.f("pk_voice_start_requests")),
        sa.UniqueConstraint("session_id", name=op.f("uq_voice_start_requests_session_id")),
    )
    # ### end Alembic commands ###
    _create_triggers()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("voice_start_requests")
    op.drop_table("voice_learning_context")
    op.drop_index(
        op.f("ix_vocabulary_observations_session_id"), table_name="vocabulary_observations"
    )
    op.drop_table("vocabulary_observations")
    op.drop_index(op.f("ix_turns_session_id"), table_name="turns")
    op.drop_index(op.f("ix_turns_provider_response_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_table("session_metrics")
    op.drop_table("session_lexicon_reports")
    op.drop_table("practice_answers")
    op.drop_table("placement_answers")
    op.drop_index(op.f("ix_lexicon_reviews_entry_id"), table_name="lexicon_reviews")
    op.drop_table("lexicon_reviews")
    op.drop_index(op.f("ix_executions_session_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_table("evaluations")
    op.drop_table("clinical_session_pins")
    op.drop_table("clinical_reviews")
    op.drop_table("clinical_publication_events")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_learner_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("profile_credentials")
    op.drop_table("practice_runs")
    op.drop_table("placement_reviews")
    op.drop_table("placement_publication_events")
    op.drop_index(op.f("ix_placement_attempts_learner_id"), table_name="placement_attempts")
    op.drop_table("placement_attempts")
    op.drop_index(op.f("ix_learner_lexicon_learner_id"), table_name="learner_lexicon")
    op.drop_table("learner_lexicon")
    op.drop_index(
        "uq_clinical_published_case_phase",
        table_name="clinical_scenarios",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_table("clinical_scenarios")
    op.drop_table("clinical_case_sources")
    op.drop_table("placement_sources")
    op.drop_table("placement_sets")
    op.drop_table("learners")
    op.drop_table("clinical_terminology")
    op.drop_table("clinical_sources")
    op.drop_table("clinical_rubrics")
    op.drop_table("clinical_cases")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS ari_practice_answer_active()")
    op.execute(ddl.DROP_IMMUTABLE_FUNCTION)


IMMUTABLE_TABLES = (
    "clinical_sources",
    "clinical_rubrics",
    "clinical_terminology",
    "clinical_cases",
    "clinical_case_sources",
    "clinical_reviews",
    "clinical_publication_events",
    "clinical_session_pins",
    "placement_sources",
    "placement_reviews",
    "placement_publication_events",
)
SCENARIO_CONTENT_COLUMNS = (
    "id",
    "version",
    "content_hash",
    "payload",
    "case_id",
    "case_version",
    "case_hash",
    "rubric_id",
    "rubric_version",
    "rubric_hash",
    "terminology_id",
    "terminology_version",
    "terminology_hash",
    "phase",
)
PLACEMENT_SET_CONTENT_COLUMNS = ("id", "version", "content_hash", "language", "payload")
PRACTICE_RUN_CONTENT_COLUMNS = (
    "id",
    "learner_id",
    "request_id",
    "mode",
    "content_hash",
    "content",
    "created_at",
)
# A WHEN clause cannot contain a subquery, so the cross-table guard is its own function.
PRACTICE_ANSWER_ACTIVE_FUNCTION = """
CREATE FUNCTION ari_practice_answer_active() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (SELECT status FROM practice_runs WHERE id = NEW.run_id) IS DISTINCT FROM 'active' THEN
    RAISE EXCEPTION 'Practice is not active' USING ERRCODE = 'integrity_constraint_violation';
  END IF;
  RETURN NEW;
END $$
"""


def _create_triggers() -> None:
    """Append-only guarantees the application relies on, enforced by the database itself."""
    op.execute(ddl.IMMUTABLE_FUNCTION)
    op.execute(PRACTICE_ANSWER_ACTIVE_FUNCTION)
    ddl.create_append_only_triggers(op, IMMUTABLE_TABLES, "Clinical content is immutable")
    ddl.create_immutable_trigger(
        op,
        "clinical_scenario_content",
        "UPDATE",
        "clinical_scenarios",
        "Immutable scenario",
        when=ddl.changed(SCENARIO_CONTENT_COLUMNS),
    )
    ddl.create_immutable_trigger(
        op, "clinical_scenario_delete", "DELETE", "clinical_scenarios", "Immutable scenario"
    )
    ddl.create_immutable_trigger(
        op,
        "placement_set_content",
        "UPDATE",
        "placement_sets",
        "Immutable placement set",
        when=ddl.changed(PLACEMENT_SET_CONTENT_COLUMNS),
    )
    ddl.create_immutable_trigger(
        op, "placement_set_delete", "DELETE", "placement_sets", "Immutable placement set"
    )
    ddl.create_immutable_trigger(
        op,
        "practice_run_immutable",
        "UPDATE",
        "practice_runs",
        "Immutable practice content/result",
        when=(
            f"{ddl.changed(PRACTICE_RUN_CONTENT_COLUMNS)} OR (OLD.status = 'completed' AND ("
            "NEW.status IS DISTINCT FROM OLD.status OR NEW.feedback IS DISTINCT FROM OLD.feedback "
            "OR NEW.ended_at IS DISTINCT FROM OLD.ended_at))"
        ),
    )
    ddl.create_append_only_triggers(op, ("practice_answers",), "Immutable answer")
    ddl.create_append_only_triggers(op, ("placement_answers",), "Immutable placement answer")
    op.execute(
        "CREATE TRIGGER practice_answer_active BEFORE INSERT ON practice_answers "
        "FOR EACH ROW EXECUTE FUNCTION ari_practice_answer_active()"
    )
    for prefix, table, message in (
        ("voice_learning", "voice_learning_context", "Immutable learning mode"),
        ("voice_start", "voice_start_requests", "Immutable start request"),
        ("lexicon_review", "lexicon_reviews", "Immutable review event"),
    ):
        for action in ("UPDATE", "DELETE"):
            ddl.create_immutable_trigger(
                op, f"{prefix}_no_{action.lower()}", action, table, message
            )
