"""learner accounts, one-time links, sessions

Revision ID: 0002_learner_accounts
Revises: 0001_initial
Create Date: 2026-09-24

Accounts are mutable bookkeeping (verification, lockout counters, the linked learner); links
and sessions record their used and revoked timestamps. Existing learners stay untouched: an
account adopts one when its browser still holds that learner's profile cookie.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_learner_accounts"
down_revision: str | Sequence[str] | None = "0001_initial"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learner_accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("learner_id", sa.String(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("failed_logins", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("email = lower(email)", name="ck_learner_account_email_lower"),
        sa.ForeignKeyConstraint(
            ["learner_id"], ["learners.id"], name=op.f("fk_learner_accounts_learner_id_learners")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learner_accounts")),
        sa.UniqueConstraint("email", name=op.f("uq_learner_accounts_email")),
        sa.UniqueConstraint("learner_id", name=op.f("uq_learner_accounts_learner_id")),
    )
    op.create_table(
        "learner_account_tokens",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('activation', 'password_reset')", name="ck_learner_token_purpose"
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["learner_accounts.id"],
            name=op.f("fk_learner_account_tokens_account_id_learner_accounts"),
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_learner_account_tokens")),
    )
    op.create_index(
        op.f("ix_learner_account_tokens_account_id"),
        "learner_account_tokens",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "learner_sessions",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["learner_accounts.id"],
            name=op.f("fk_learner_sessions_account_id_learner_accounts"),
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_learner_sessions")),
    )
    op.create_index(
        op.f("ix_learner_sessions_account_id"), "learner_sessions", ["account_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_learner_sessions_account_id"), table_name="learner_sessions")
    op.drop_table("learner_sessions")
    op.drop_index(op.f("ix_learner_account_tokens_account_id"), table_name="learner_account_tokens")
    op.drop_table("learner_account_tokens")
    op.drop_table("learner_accounts")
    # ### end Alembic commands ###
