"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-09-14 17:19:40.361535
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_initial"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clinical_cases",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
        sa.UniqueConstraint("id", "version", "content_hash"),
    )
    op.create_table(
        "clinical_rubrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
        sa.UniqueConstraint("id", "version", "content_hash"),
    )
    op.create_table(
        "clinical_sources",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_terminology",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", "version"),
        sa.UniqueConstraint("id", "version", "content_hash"),
    )
    op.create_table(
        "learners",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("goal", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_case_sources",
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["case_id", "case_version"],
            ["clinical_cases.id", "clinical_cases.version"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["clinical_sources.id"],
        ),
        sa.PrimaryKeyConstraint("case_id", "case_version", "source_id"),
    )
    op.create_table(
        "clinical_scenarios",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(length=64), nullable=False),
        sa.Column("rubric_id", sa.String(), nullable=False),
        sa.Column("rubric_version", sa.String(), nullable=False),
        sa.Column("rubric_hash", sa.String(length=64), nullable=False),
        sa.Column("terminology_id", sa.String(), nullable=False),
        sa.Column("terminology_version", sa.String(), nullable=False),
        sa.Column("terminology_hash", sa.String(length=64), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.CheckConstraint(
            "phase IN ('arzt_patient', 'arzt_arzt', 'fachbegriffe', 'arztbrief')",
            name="ck_clinical_phase",
        ),
        sa.CheckConstraint(
            "status IN ('draft_unvalidated', 'published', 'withdrawn')",
            name="ck_clinical_workflow_status",
        ),
        sa.ForeignKeyConstraint(
            ["case_id", "case_version", "case_hash"],
            ["clinical_cases.id", "clinical_cases.version", "clinical_cases.content_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["rubric_id", "rubric_version", "rubric_hash"],
            ["clinical_rubrics.id", "clinical_rubrics.version", "clinical_rubrics.content_hash"],
        ),
        sa.ForeignKeyConstraint(
            ["terminology_id", "terminology_version", "terminology_hash"],
            [
                "clinical_terminology.id",
                "clinical_terminology.version",
                "clinical_terminology.content_hash",
            ],
        ),
        sa.PrimaryKeyConstraint("id", "version"),
        sa.UniqueConstraint("id", "version", "content_hash"),
    )
    op.create_index(
        "uq_clinical_published_case_phase",
        "clinical_scenarios",
        ["case_id", "case_version", "phase"],
        unique=True,
        sqlite_where=sa.text("status = 'published'"),
    )
    op.create_table(
        "practice_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", sa.JSON(none_as_null=True), nullable=False),
        sa.Column("feedback", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "(status = 'completed' AND feedback IS NOT NULL AND ended_at IS NOT NULL) OR "
            "(status != 'completed' AND feedback IS NULL AND ended_at IS NULL)",
            name="ck_practice_feedback_state",
        ),
        sa.CheckConstraint("mode IN ('training','exam')", name="ck_practice_mode"),
        sa.CheckConstraint("status IN ('active','paused','completed')", name="ck_practice_status"),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("learner_id", "request_id", name="uq_practice_start_request"),
    )
    op.create_table(
        "profile_credentials",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("token_hash"),
        sa.UniqueConstraint("learner_id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=False),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(), nullable=False),
        sa.Column("goal", sa.JSON(), nullable=False),
        sa.Column("voice_profile", sa.String(), nullable=False),
        sa.Column("interaction_mode", sa.String(), nullable=False),
        sa.Column("voice_stack_id", sa.String(), nullable=False),
        sa.Column("voice_stack_version", sa.String(), nullable=False),
        sa.Column("voice_stack_config", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("call_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_learner_id"), "sessions", ["learner_id"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    op.create_table(
        "clinical_publication_events",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version"],
            ["clinical_scenarios.id", "clinical_scenarios.version"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clinical_reviews",
        sa.Column("sequence", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("scenario_hash", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version", "scenario_hash"],
            [
                "clinical_scenarios.id",
                "clinical_scenarios.version",
                "clinical_scenarios.content_hash",
            ],
        ),
        sa.PrimaryKeyConstraint("sequence"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "clinical_session_pins",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("scenario_id", sa.String(), nullable=False),
        sa.Column("scenario_version", sa.String(), nullable=False),
        sa.Column("scenario_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_id", "scenario_version", "scenario_hash"],
            [
                "clinical_scenarios.id",
                "clinical_scenarios.version",
                "clinical_scenarios.content_hash",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "evaluations",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "executions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=True),
        sa.Column("prompt_hash", sa.String(), nullable=True),
        sa.Column("case_version", sa.String(), nullable=False),
        sa.Column("case_hash", sa.String(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("usage", sa.JSON(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.Column("pricing_version", sa.String(), nullable=False),
        sa.Column("cost_status", sa.String(), nullable=False),
        sa.Column("cost_amount_usd", sa.Float(), nullable=True),
        sa.Column("cost_units", sa.JSON(), nullable=False),
        sa.Column("cost_assumptions", sa.JSON(), nullable=False),
        sa.Column("cost_unknown_reason", sa.Text(), nullable=True),
        sa.Column("provider_request_id", sa.String(), nullable=True),
        sa.Column("turn_id", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_executions_session_id"), "executions", ["session_id"], unique=False)
    op.create_table(
        "patient_openings",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("spoken_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("provider_response_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "practice_answers",
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(none_as_null=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["practice_runs.id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "question_id"),
        sa.UniqueConstraint("run_id", "event_id", name="uq_practice_answer_event"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_practice_answer_sequence"),
    )
    op.create_table(
        "session_metrics",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("user_text", sa.Text(), nullable=False),
        sa.Column("patient_text", sa.Text(), nullable=False),
        sa.Column("revealed_fact_ids", sa.JSON(), nullable=False),
        sa.Column("selected_fact_ids", sa.JSON(), nullable=False),
        sa.Column("provider_input_item_id", sa.String(), nullable=True),
        sa.Column("provider_response_id", sa.String(), nullable=True),
        sa.Column("interrupted", sa.Boolean(), nullable=False),
        sa.Column("interruption_audio_end_ms", sa.Integer(), nullable=True),
        sa.Column("provider_response_status", sa.String(), nullable=False),
        sa.Column("response_state", sa.String(), nullable=False),
        sa.Column("delivery_status", sa.String(), nullable=False),
        sa.Column("audio_stream_id", sa.String(), nullable=True),
        sa.Column("audio_attempt", sa.Integer(), nullable=False),
        sa.Column("expected_audio_chunks", sa.Integer(), nullable=True),
        sa.Column("audio_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("audio_delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("normalized_user_text", sa.Text(), nullable=True),
        sa.Column("canonical_response", sa.JSON(), nullable=True),
        sa.Column("observed_response_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "provider_input_item_id", name="uq_turn_session_input_item"
        ),
        sa.UniqueConstraint("session_id", "provider_response_id", name="uq_turn_session_response"),
        sa.UniqueConstraint("session_id", "sequence"),
    )
    op.create_index(
        op.f("ix_turns_provider_response_id"), "turns", ["provider_response_id"], unique=False
    )
    op.create_index(op.f("ix_turns_session_id"), "turns", ["session_id"], unique=False)
    op.create_table(
        "vocabulary_hint_usages",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("hint_id", sa.String(), nullable=False),
        sa.Column("asset_version", sa.String(), nullable=False),
        sa.Column("usage_count", sa.Integer(), nullable=False),
        sa.Column("first_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id", "hint_id"),
    )
    op.create_table(
        "vocabulary_observations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("lemma", sa.String(), nullable=False),
        sa.Column("translation", sa.String(), nullable=False),
        sa.Column("example", sa.Text(), nullable=False),
        sa.Column("evidence_turn_sequences", sa.JSON(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vocabulary_observations_session_id"),
        "vocabulary_observations",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "voice_learning_context",
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.CheckConstraint("mode IN ('training','exam')", name="ck_voice_learning_mode"),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "voice_start_requests",
        sa.Column("learner_id", sa.String(), nullable=False),
        sa.Column("request_id", sa.String(), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["learner_id"],
            ["learners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("learner_id", "request_id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "voice_stack_transitions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("from_stack_id", sa.String(), nullable=False),
        sa.Column("from_stack_version", sa.String(), nullable=False),
        sa.Column("from_stack_config", sa.JSON(), nullable=False),
        sa.Column("to_stack_id", sa.String(), nullable=False),
        sa.Column("to_stack_version", sa.String(), nullable=False),
        sa.Column("to_stack_config", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("failure_execution_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["failure_execution_id"],
            ["executions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id",
            "from_stack_id",
            "to_stack_id",
            "failure_execution_id",
            name="uq_voice_stack_transition_request",
        ),
    )
    op.create_index(
        op.f("ix_voice_stack_transitions_session_id"),
        "voice_stack_transitions",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "voice_turn_metrics",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("turn_id", sa.String(), nullable=False),
        sa.Column("schema_version", sa.String(), nullable=False),
        sa.Column("trace_id", sa.String(), nullable=False),
        sa.Column("voice_stack_id", sa.String(), nullable=False),
        sa.Column("voice_stack_version", sa.String(), nullable=False),
        sa.Column("transport", sa.String(), nullable=False),
        sa.Column("models", sa.JSON(), nullable=False),
        sa.Column("provider_ids", sa.JSON(), nullable=False),
        sa.Column("case_id", sa.String(), nullable=True),
        sa.Column("case_version", sa.String(), nullable=True),
        sa.Column("case_hash", sa.String(), nullable=True),
        sa.Column("interaction_mode", sa.String(), nullable=True),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.Column("prompt_hashes", sa.JSON(), nullable=False),
        sa.Column("delivery_status", sa.String(), nullable=False),
        sa.Column("application_version", sa.String(), nullable=True),
        sa.Column("clock_domains", sa.JSON(), nullable=False),
        sa.Column("wall_timestamps_utc", sa.JSON(), nullable=False),
        sa.Column("speech_end_to_transcript_final_ms", sa.Integer(), nullable=True),
        sa.Column("transcript_final_to_llm_first_token_ms", sa.Integer(), nullable=True),
        sa.Column("llm_total_ms", sa.Integer(), nullable=True),
        sa.Column("llm_complete_to_tts_first_byte_ms", sa.Integer(), nullable=True),
        sa.Column("tts_total_ms", sa.Integer(), nullable=True),
        sa.Column("speech_end_to_first_audio_sent_ms", sa.Integer(), nullable=True),
        sa.Column("speech_end_to_audio_started_ms", sa.Integer(), nullable=True),
        sa.Column("audio_sent_to_playback_started_ms", sa.Integer(), nullable=True),
        sa.Column("speech_end_to_transcript_ms", sa.Integer(), nullable=True),
        sa.Column("transcript_to_first_token_ms", sa.Integer(), nullable=True),
        sa.Column("first_token_to_first_audio_ms", sa.Integer(), nullable=True),
        sa.Column("speech_end_to_first_audio_ms", sa.Integer(), nullable=True),
        sa.Column("turn_total_ms", sa.Integer(), nullable=True),
        sa.Column("interruption_count", sa.Integer(), nullable=False),
        sa.Column("error_count", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('completed', 'failed')", name="ck_voice_turn_metrics_status"
        ),
        sa.CheckConstraint(
            "transport IN ('realtime', 'pipeline')", name="ck_voice_turn_metrics_transport"
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["turn_id"],
            ["turns.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_voice_turn_metrics_session_id"), "voice_turn_metrics", ["session_id"], unique=False
    )
    op.create_index(
        op.f("ix_voice_turn_metrics_trace_id"), "voice_turn_metrics", ["trace_id"], unique=False
    )
    op.create_index(
        op.f("ix_voice_turn_metrics_turn_id"), "voice_turn_metrics", ["turn_id"], unique=False
    )
    _create_sqlite_triggers()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_turn_metrics_turn_id"), table_name="voice_turn_metrics")
    op.drop_index(op.f("ix_voice_turn_metrics_trace_id"), table_name="voice_turn_metrics")
    op.drop_index(op.f("ix_voice_turn_metrics_session_id"), table_name="voice_turn_metrics")
    op.drop_table("voice_turn_metrics")
    op.drop_index(
        op.f("ix_voice_stack_transitions_session_id"), table_name="voice_stack_transitions"
    )
    op.drop_table("voice_stack_transitions")
    op.drop_table("voice_start_requests")
    op.drop_table("voice_learning_context")
    op.drop_index(
        op.f("ix_vocabulary_observations_session_id"), table_name="vocabulary_observations"
    )
    op.drop_table("vocabulary_observations")
    op.drop_table("vocabulary_hint_usages")
    op.drop_index(op.f("ix_turns_session_id"), table_name="turns")
    op.drop_index(op.f("ix_turns_provider_response_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_table("session_metrics")
    op.drop_table("practice_answers")
    op.drop_table("patient_openings")
    op.drop_index(op.f("ix_executions_session_id"), table_name="executions")
    op.drop_table("executions")
    op.drop_table("evaluations")
    op.drop_table("clinical_session_pins")
    op.drop_table("clinical_reviews")
    op.drop_table("clinical_publication_events")
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_learner_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("profile_credentials")
    op.drop_table("practice_runs")
    op.drop_index(
        "uq_clinical_published_case_phase",
        table_name="clinical_scenarios",
        sqlite_where=sa.text("status = 'published'"),
    )
    op.drop_table("clinical_scenarios")
    op.drop_table("clinical_case_sources")
    op.drop_table("learners")
    op.drop_table("clinical_terminology")
    op.drop_table("clinical_sources")
    op.drop_table("clinical_rubrics")
    op.drop_table("clinical_cases")
    # ### end Alembic commands ###


IMMUTABLE_CLINICAL_TABLES = (
    "clinical_sources",
    "clinical_rubrics",
    "clinical_terminology",
    "clinical_cases",
    "clinical_case_sources",
    "clinical_reviews",
    "clinical_publication_events",
    "clinical_session_pins",
)
SCENARIO_CONTENT_COLUMNS = (
    "id",
    "version",
    "content_hash",
    "payload",
    "case_id",
    "case_version",
    "case_hash",
    "rubric_id",
    "rubric_version",
    "rubric_hash",
    "terminology_id",
    "terminology_version",
    "terminology_hash",
    "phase",
)
PRACTICE_RUN_CONTENT_COLUMNS = (
    "id",
    "learner_id",
    "request_id",
    "mode",
    "content_hash",
    "content",
    "created_at",
)


def _abort(name: str, event: str, table: str, message: str, when: str = "") -> None:
    op.execute(
        f"CREATE TRIGGER {name} BEFORE {event} ON {table} {when}"
        f"BEGIN SELECT RAISE(ABORT, '{message}'); END"
    )


def _create_sqlite_triggers() -> None:
    """Append-only guarantees that the application relies on; SQLite has no row locks."""
    for table in IMMUTABLE_CLINICAL_TABLES:
        for action in ("UPDATE", "DELETE"):
            _abort(f"{table}_no_{action.lower()}", action, table, "Clinical content is immutable")
    changed = " OR ".join(f"NEW.{c} IS NOT OLD.{c}" for c in SCENARIO_CONTENT_COLUMNS)
    _abort(
        "clinical_scenario_content",
        "UPDATE",
        "clinical_scenarios",
        "Immutable scenario",
        when=f"WHEN {changed} ",
    )
    _abort("clinical_scenario_delete", "DELETE", "clinical_scenarios", "Immutable scenario")
    changed = " OR ".join(f"NEW.{c} IS NOT OLD.{c}" for c in PRACTICE_RUN_CONTENT_COLUMNS)
    _abort(
        "practice_run_immutable",
        "UPDATE",
        "practice_runs",
        "Immutable practice content/result",
        when=(
            f"WHEN {changed} OR (OLD.status = 'completed' AND (NEW.status IS NOT OLD.status "
            "OR NEW.feedback IS NOT OLD.feedback OR NEW.ended_at IS NOT OLD.ended_at)) "
        ),
    )
    for action in ("UPDATE", "DELETE"):
        _abort(
            f"practice_answers_no_{action.lower()}", action, "practice_answers", "Immutable answer"
        )
    _abort(
        "practice_answer_active",
        "INSERT",
        "practice_answers",
        "Practice is not active",
        when="WHEN (SELECT status FROM practice_runs WHERE id=NEW.run_id) != 'active' ",
    )
    for prefix, table, message in (
        ("voice_learning", "voice_learning_context", "Immutable learning mode"),
        ("voice_start", "voice_start_requests", "Immutable start request"),
    ):
        for action in ("UPDATE", "DELETE"):
            _abort(f"{prefix}_no_{action.lower()}", action, table, message)
